### ISSUE TITLE
Change default molecule platform

### ISSUE THREAD

**Issue by pa-decarvalho** [pa-decarvalho/ansible-collection-template#1]
```yml
platforms:
  - name: ${USER}-{{ collection_name | replace('_', '-') }}-${MOLECULE_DISTRO:-ubuntu2404}
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
```
