### ISSUE TITLE
Add Task command molecule:reconverge

### ISSUE THREAD

**Issue by pa-decarvalho** [pa-decarvalho/ansible-collection-template#12]
```yml
reconverge:
    desc: Run molecule destroy & converge
    silent: true
    cmds:
      - poetry run molecule destroy
      - poetry run molecule converge
```
