### ISSUE TITLE
Add .gitpod/automations.yaml file

### ISSUE THREAD

**Issue by pa-decarvalho** [pa-decarvalho/ansible-collection-template#18]
```yml
---
tasks:
  init:
    name: Init dev project
    command: |
      task init
    triggeredBy:
      - postEnvironmentStart

```
