### ISSUE TITLE
Change molecule provisioner

### ISSUE THREAD

**Issue by pa-decarvalho** [pa-decarvalho/ansible-collection-template#2]
```yml
provisioner:
  name: ansible
  options:
    vvv: true
  env:
    ANSIBLE_ROLES_PATH: ../../roles
```

```yml
provisioner:
  name: ansible
```
