### ISSUE TITLE
Add molecule verify

### ISSUE THREAD

**Issue by pa-decarvalho** [pa-decarvalho/ansible-collection-template#3]
`molecule/default/verify.yml`

```yml
---
- name: Verify
  hosts: all
  tasks:
    - name: Verify example
      ansible.builtin.debug:
        msg: Hello world !
```
