### ISSUE TITLE
Change Task test

### ISSUE THREAD

**Issue by pa-decarvalho** [pa-decarvalho/ansible-collection-template#9]
In `taskfile.yml`

```yml
test:
    desc: Reinit project
    silent: true
    cmds:
      - poetry run molecule test
```

```yml
test:
    desc: Run tests
    silent: true
    cmds:
      - task: molecule:test
```
